metabolite_database/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SelectMultipleField, SubmitField, widgets
from wtforms.validators import DataRequired, InputRequired


class MultiCheckboxField(SelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class RetentionTimesForm(FlaskForm):
    compoundlist = SelectField('Compound List', coerce=int,
                               validators=[InputRequired()])
    standardruns = MultiCheckboxField(
        'Standard Runs', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Get List')

metabolite_database/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from metabolite_database.main import routes  # noqa

metabolite_database/main/routes.py
from itertools import groupby
from operator import attrgetter
from flask import (render_template, current_app, redirect, url_for)
from metabolite_database.models import (Compound, ChromatographyMethod,
                                        StandardRun, CompoundList)
from metabolite_database.main import bp
from metabolite_database.main.forms import RetentionTimesForm


@bp.route('/')
@bp.route('/index')
def index():
    return redirect(url_for('main.methods'))


@bp.route('/compounds')
def compounds():
    compounds = Compound.query.all()
    return render_template('main/compound_list.html',
                           title="All Compounds",
                           description="All compounds in the database",
                           compounds=compounds)


@bp.route('/compound/<id>')
def compound(id):
    compound = Compound.query.filter_by(id=id).first_or_404()
    return render_template('main/compound.html',
                           title=compound.name, compound=compound)


@bp.route('/compound_lists')
def compound_lists():
    compound_lists = CompoundList.query.all()
    return render_template('main/compound_lists.html',
                           title="Compound Lists",
                           compound_lists=compound_lists)


@bp.route('/compound_list/<id>')
def compound_list(id):
    compound_list = CompoundList.query.filter_by(id=id).first_or_404()
    return render_template('main/compound_list.html',
                           title=compound_list.name,
                           description=compound_list.description,
                           compounds=compound_list.compounds)


@bp.route('/methods')
def methods():
    methods = ChromatographyMethod.query.all()
    return render_template('main/methods.html',
                           title="Chromatography Methods", methods=methods)


@bp.route('/method/<id>', methods=['GET', 'POST'])
def method(id):
    method = ChromatographyMethod.query.filter_by(id=id).first_or_404()
    compound_lists = [(0, "All ({} compounds)".format(
        Compound.query.count()))]
    compound_lists.extend([(cl.id, "{} ({} compounds)".format(
        cl.name, len(cl.compounds))) for cl in CompoundList.query.all()])
    standard_runs = [
        (r.id, "Run on {:%Y-%m-%d} by {} ({} retention times)".format(
            r.date, r.operator, len(r.retention_times)))
        for r in method.standard_runs]
    form = RetentionTimesForm(
        compoundlist=0,
        standardruns=[r.id for r in method.standard_runs])
    form.compoundlist.choices = compound_lists
    form.standardruns.choices = standard_runs
    retention_times = None
    current_app.logger.debug("compound list data: {}".format(
        form.compoundlist.data))
    if form.validate_on_submit():
        retention_times = method.retention_time_means(
            compound_list_id=form.compoundlist.data,
            standard_run_ids=form.standardruns.data)
        if form.submit.data:
            current_app.logger.debug("Select form submitted")
    if not form.standardruns.data:
        form.standardruns.process_data([r.id for r in method.standard_runs])
    return render_template(
        'main/method.html',
        title="{} method".format(method.name),
        method=method,
        form=form,
        retention_times=retention_times)


@bp.route('/standard_runs')
@bp.route('/standardruns')
@bp.route('/standard-runs')
def standard_runs():
    runs = StandardRun.query.all()
    return render_template('main/standard_runs.html',
                           title="Standard runs", runs=runs)


@bp.route('/standard_run/<id>')
@bp.route('/standardrun/<id>')
@bp.route('/standard-run/<id>')
def standard_run(id):
    run = StandardRun.query.filter_by(id=id).first_or_404()
    # TODO Fix date represntation (how to use moment for format?)
    return render_template('main/standard_run.html',
                           title="Standard run: {}".format(run.date), run=run)


@bp.route('/isomers')
def isomers():
    compounds = Compound.query.order_by(Compound.molecular_formula).all()
    isomer_groups = [list(c) for k, c in
                     groupby(compounds, attrgetter('molecular_formula'))]
    isomer_groups = [item for item in isomer_groups if len(item) > 1]
    return render_template('main/isomers.html',
                           title="List of isomers",
                           isomer_groups=isomer_groups)

metabolite_database/templates/main/compound.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#standard_runs').DataTable();
      $('#isomers').DataTable();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>{{ compound.name }}</h1>
  <p>
    <strong>{{ compound.molecular_formula }}</strong> (<a target="_blank"
    href="http://www.hmdb.ca/unearth/q?utf8=%E2%9C%93&query=name%3A%22{{ compound.name | urlencode }}%22+AND+chemical_formula%3A{{ compound.molecular_formula }}&searcher=metabolites&button=">Search
    HMDB</a>)
  </p>
  {% if compound.notes %}
  <p>{{ compound.notes }}</p>
  {% endif %}
  <dl>
    <dt>Monoisotopic Mass</dt>
    <dd>{{ compound.monoisotopic_mass }}</dd>
    <dt>m/z (positive mode)</dt>
    <dd>{{ compound.m_z(1) }}
    <dt>m/z (negative mode)</dt>
    <dd>{{ compound.m_z(-1) }}</dd>
  </dl>

  <h2>Isomers</h2>
  {% if compound.isomers|length > 0 %}
  <table id="isomers" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Notes</th>
        <th>Retetion Times</th>
        <th>Compound Lists</th>
      </tr>
    </thead>
    <tbody>
      {% for isomer in compound.isomers %}
        <tr>
          <td><a href="{{ url_for('main.compound', id=isomer.id) }}">
              {{ isomer.name }}</a></td>
          <td>{{ isomer.notes }}</td>
          <td>{{ isomer.retention_times | length }}</td>
          <td>{{ isomer.compound_lists | length }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No isomers in database</p>
  {% endif %}

  <h2>Compound Lists</h2>
  {% if compound.compound_lists|length > 0 %}
  <ul>
    {% for list in compound.compound_lists %}
      <li><a href="{{ url_for('main.compound_list', id=list.id) }}">{{ list.name }}:
          {{ list.description }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>Compound is not part of any compound lists</p>
  {% endif %}

  <h2>Standard Runs</h2>
  <table id="standard_runs" class="table">
    <thead>
      <tr>
        <th>Method</th>
        <th>Retetion Time</th>
      </tr>
    </thead>
    <tbody>
      {% for rt in compound.retention_times %}
        <tr>
          <td><a href="{{ url_for('main.methods') }}">
              {{ rt.standard_run.chromatography_method.name }}</a></td>
          <td>{{ rt.retention_time }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

metabolite_database/templates/main/compound_list.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#compound_list').DataTable({
        pageLength: 50
      });
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>{{ title }}</h1>
  <p>{{ description }}</p>
  <p>{{ compounds | length }} compounds</p>

  <h2>Compounds</h2>
  <table id="compound_list" class="table" style="width:100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Formula</th>
        <th>Monoisotopic Mass</th>
        <th>m/z (positive mode)</th>
        <th>m/z (negative mode)</th>
        <th>Isomers</th>
        <th>Notes</th>
        <th>Retetion Times</th>
        <th>Compound Lists</th>
      </tr>
    </thead>
    <tbody>
      {% for compound in compounds %}
        <tr>
          <td><a href="{{ url_for('main.compound', id=compound.id) }}">
              {{ compound.name }}</a></td>
          <td>{{ compound.molecular_formula }}</td>
          <td>{{ '{0:0.4f}'.format(compound.monoisotopic_mass) }}</td>
          <td>{{ '{0:0.4f}'.format(compound.m_z(1)) }}</td>
          <td>{{ '{0:0.4f}'.format(compound.m_z(-1)) }}</td>
          <td>{{ compound.isomers | length }}
          <td>{{ compound.notes }}</td>
          <td>{{ compound.retention_times | length }}</td>
          <td>{{ compound.compound_lists | length }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

metabolite_database/templates/main/compound_lists.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#compound_lists').DataTable();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>Compound Lists</h1>
  <table id="compound_lists" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Compounds</th>
      </tr>
    </thead>
    <tbody>
      {% for compound_list in compound_lists %}
        <tr>
          <td><a href="{{ url_for('main.compound_list', id=compound_list.id) }}">{{ compound_list.name }}</a></td>
          <td><a href="{{ url_for('main.compound_list', id=compound_list.id) }}">{{ compound_list.description }}</a></td>
          <td><a href="{{ url_for('main.compound_list', id=compound_list.id) }}">{{ compound_list.compounds | length }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

metabolite_database/templates/main/index.html
{% extends "base.html" %}

{% block app_content %}
  <h1>Hi, {{ user.username }}!</h1>
  {% for post in posts %}
    <div>
      <p>{{ post.author.username }} says: <b>{{ post.body }}</b></p>
    </div>
  {% endfor %}
{% endblock %}

metabolite_database/templates/main/isomers.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#isomers').DataTable();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>{{ title }}</h1>

  <h2>Isomers Groups ({{ isomer_groups | length }})</h2>
  {% for isomer_group in isomer_groups %}
    <h4>{{ isomer_group[0].molecular_formula }}</h4>
    <ul class="list-group">
    {% for isomer in isomer_group %}
    <li class="list-group-item">
      <a href="{{ url_for('main.compound', id=isomer.id) }}">{{ isomer.name }}</a>
    </li>
    {% endfor %}
  </ul>
  {% endfor %}
{% endblock %}

metabolite_database/templates/main/method.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      var data_table = $('#retention_time_table').DataTable( {
        buttons: [
          'pageLength',
          {
            extend: 'csv',
            text: 'Export',
            exportOptions: {
              columns: [0, 1, 3, 5],
              format: {
                header: function(data, column, node) {
                  switch(column) {
                    case 0:
                      return "compound";
                    case 1:
                      return "formula";
                    case 3:
                      return "RT";
                    case 5:
                      return "note";
                    default:
                      return data;
                  }
                }
              }
            }
          },
          {
            text: 'Group isomers',
            action: function() {
              data_table.rowGroup().enable();
              data_table.columns(4).search('[^0]', true, false);
              data_table.order.fixed([[1, 'asc']]);
              data_table.draw();
            }
          },
          {
            text: 'Ungroup',
            action: function() {
              data_table.rowGroup().disable();
              data_table.columns(4).search('', true, false);
              data_table.order.fixed([]);
              data_table.draw();
            }
          },      
        ],
        rowGroup: {
          enable: false,
          dataSrc: 1
        },
        pageLength: 50,
        lengthChange: false,
        order: [[1, 'asc']]
      });
      data_table.buttons().container()
        .appendTo( $('#retention_time_table_wrapper .col-sm-12:eq(0)' ) );
      data_table.rowGroup().disable().draw();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1><strong>{{ method.name }}</strong></h1>

  <h2>Select Compounds and Standard Runs</h2>
  {% from 'bootstrap/form.html' import render_field, form_errors %}
  <form class="form" method="post" role="form" action="" novalidate>
    <div class="row">
      <div class="col-sm">
        {{ form.csrf_token() }}
        {{ form_errors(form, hiddens="only") }}

        {{ render_field(form.compoundlist) }}
      </div>
      <div class="col-sm">
        {{ form.standardruns.label }}
        <p><em>Note: </em>When multiple standard runs are selected, the retention
          times reported are the average from each selected run.</p>
        {% for error in form.standardruns.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
        {% for choice in form.standardruns %}
          <div class="form-check">
            {{ choice(checked=choice.checked, class="form-check-input") }}
            {{ choice.label(class="form-check-label") }}
            <a href="{{ url_for('main.standard_run', id=choice.data) }}">Details</a>
          </div>
        </div>
        {% endfor %}
      </div>

    {{ render_field(form.submit) }}
  </form>

  {% if retention_times is not none %}
  <p/>
  <h2>Mean Retiontion Times</h2>
  <table id="retention_time_table" class="table">
    <thead>
      <tr>
        <th>Compound</th>
        <th>Formula</th>
        <th>Monoisotopic mass</th>
        <th>Mean Retention Time (sec)</th>
        <th>Isomers</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      {% for compound, mean_rt in retention_times %}
        <tr>
          <td><a href="{{ url_for('main.compound', id=compound.id) }}">
              {{ compound.name }}</a></td>
          <td>{{ compound.molecular_formula }}</td>
          <td>{{ compound.monoisotopic_mass }}</td>
          {% if mean_rt is none %}
            <td class="warning"></td>
          {% else %}
            <td>{{ mean_rt }}</td>
          {% endif %}
          <td>{{ compound.isomers | length }}</td>
          <td>{{ compound.notes if compound.notes }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

metabolite_database/templates/main/methods.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#methods').DataTable();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>Chromatography Methods</h1>
  <table id="methods" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Number of Standard Runs</th>
        <th>Compounds with Retention Times</th>
      </tr>
    </thead>
    <tbody>
      {% for method in methods %}
        <tr>
          <td><a href="{{ url_for('main.method', id=method.id) }}">{{ method.name }}</a></td>
          <td><a href="{{ url_for('main.method', id=method.id) }}">{{ method.description }}</a></td>
          <td><a href="{{ url_for('main.method', id=method.id) }}">{{ method.standard_runs | length }}</a></td>
          <td><a href="{{ url_for('main.method', id=method.id) }}">
              {{ method.unique_compounds_with_retention_times().count() }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

metabolite_database/templates/main/retention_times.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Retention Times for Method "{{ method.name }}"</h1>
    <table class="table">
        <tr>
            <th>Compound</th>
            <th>Formula</th>
            <th>Weight</th>
            <th>Retention Time (sec)</th>
        </tr>
        {% for compound, rt in results %}
            <tr>
                <td><a href="{{ url_for('main.compound', id=compound.id) }}">
                    {{ compound.name }}</a></td>
                <td>{{ compound.molecular_formula }}</td>
                <td>{{ compound.molecular_weight }}</td>
                <td>{{ rt.retention_time}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

metabolite_database/templates/main/standard_run.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#retention_times').DataTable( {
        pageLength: 50
      });
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>Standard Run: {{ moment(run.date).format('LL') }}</h1>
  <p>{{ run.notes }}</p>
  <dl>
    <dt>Method</dt>
    <dd><a href="{{ url_for('main.method', id=run.chromatography_method.id) }}">{{ run.chromatography_method.name }}</a></dd>
    <dt>Date</dt>
    <dd>{{ moment(run.date).format('L') }}</dd>
    <dt>Operator</dt>
    <dd>{{ run.operator }}</dd>
    <dt>mzXML File</dt>
    <dd>{{ run.mzxml_file }}</dd>
  </dl>
  <table id="retention_times" class="table">
    <thead>
      <tr>
        <th>Compound</th>
        <th>Retetion Time</th>
      </tr>
    </thead>
    <tbody>
      {% for rt in run.retention_times %}
        <tr>
          <td><a href="{{ url_for('main.compound', id=rt.compound.id) }}">
              {{ rt.compound.name }}</a></td>
          {% if rt.retention_time is none %}
            <td class="warning">
          {% else %}
            <td>
          {% endif %}
            {{ rt.retention_time }}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

metabolite_database/templates/main/standard_runs.html
{% extends "base.html" %}

{% block scripts %}
  {{super()}}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#standard_runs').DataTable();
    });
  </script>
{% endblock %}

{% block app_content %}
  <h1>Standard Runs</h1>
  <table id="standard_runs" class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Operator</th>
        <th>MzXML File</th>
        <th>Compound Retetion Times</th>
      </tr>
    </thead>
    <tbody>
      {% for run in runs %}
        <tr>
          <td><a href="{{url_for('main.standard_run', id=run.id) }}">{{ moment(run.date).format('LLL') }}</a></td>
          <td><a href="{{url_for('main.standard_run', id=run.id) }}">{{ run.operator}}</a></td>
          <td><a href="{{url_for('main.standard_run', id=run.id) }}">{{ run.mzxml_file }}</a></td>
          <td><a href="{{url_for('main.standard_run', id=run.id) }}">{{ run.retention_times|length }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}